const $=s=>document.querySelector(s);
const money=n=>Number(n).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
let products=[],cart={},category="Todos";
async function load(){try{const r=await fetch("/api/products");products=await r.json();renderCategories();renderProducts()}catch{$("#products").innerHTML="<p>Não foi possível carregar a loja. Tente novamente.</p>"}}
function renderCategories(){const cats=["Todos",...new Set(products.map(p=>p.category))];$("#categories").innerHTML=cats.map(c=>`<button class="${c===category?"active":""}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");$("#categories").querySelectorAll("button").forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderCategories();renderProducts()})}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderProducts(){const q=$("#search").value.toLowerCase();const list=products.filter(p=>(category==="Todos"||p.category===category)&&(p.name+" "+p.description).toLowerCase().includes(q));$("#products").innerHTML=list.length?list.map(p=>`<article class="product"><div class="pic">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:"🐾"}</div><div class="product-body"><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p class="desc">${esc(p.description)}</p><small>${p.stock>0?`${p.stock} em estoque`:"Indisponível"}</small><div class="price-row"><span class="price">${money(p.price)}</span><button class="add" data-add="${p.id}" ${p.stock<1?"disabled":""} aria-label="Adicionar ${esc(p.name)}">+</button></div></div></article>`).join(""):"<p>Nenhum produto encontrado.</p>";$("#products").querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(Number(b.dataset.add)))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;cart[id]=(cart[id]||0)+1;if(cart[id]>p.stock)cart[id]=p.stock;renderCart()}
function change(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];else{const p=products.find(x=>x.id===id);if(cart[id]>p.stock)cart[id]=p.stock}renderCart()}
function renderCart(){const entries=Object.entries(cart);$("#cartCount").textContent=entries.reduce((s,[,q])=>s+q,0);$("#cartItems").innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===Number(id));return `<div class="cart-line"><div><strong>${esc(p.name)}</strong><small>${money(p.price)} cada</small></div><div class="qty"><button data-dec="${id}">−</button><b>${q}</b><button data-inc="${id}">+</button></div></div>`}).join(""):"<p>Seu carrinho está vazio.</p>";$("#cartTotal").textContent=money(entries.reduce((s,[id,q])=>s+Number(products.find(p=>p.id===Number(id)).price)*q,0));$("#cartItems").querySelectorAll("[data-dec]").forEach(b=>b.onclick=()=>change(Number(b.dataset.dec),-1));$("#cartItems").querySelectorAll("[data-inc]").forEach(b=>b.onclick=()=>change(Number(b.dataset.inc),1))}
$("#search").addEventListener("input",renderProducts);
$("#cartOpen").onclick=()=>$("#cartDialog").showModal();$("#cartClose").onclick=()=>$("#cartDialog").close();
$("#checkout").onsubmit=async e=>{e.preventDefault();if(!Object.keys(cart).length){$("#checkoutMessage").textContent="Adicione produtos antes de enviar.";return}const form=new FormData(e.target);const payload=Object.fromEntries(form.entries());payload.items=Object.entries(cart).map(([product_id,quantity])=>({product_id:Number(product_id),quantity}));const btn=e.target.querySelector("button");btn.disabled=true;btn.textContent="Enviando...";try{const r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error);$("#checkoutMessage").textContent=`${data.message} Número do pedido: #${data.order.id}`;cart={};e.target.reset();await load();renderCart()}catch(err){$("#checkoutMessage").textContent=err.message}finally{btn.disabled=false;btn.textContent="Enviar pedido"}};
load();renderCart();